### ISSUE TITLE
[SUGGESTION] add smooth transition between dark and light mode to save eyes

### ISSUE THREAD

**Issue by unseeyou** [AndrewPerson/Lit-Paragon-Client#180]
example from unseeyou.pages.dev:

```css
body {
  display: flex;
  flex-direction: column;
  align-items: default;
  justify-content: center;
  background: var(--color-2);
  transition: background 0.3s;
}
```
transition works on most clients so don't worry about it being red on vs code
